# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a dataset which contains information on World Cup matches. Let's use the Pandas commands learned in the previous lesson to learn more about our data!

## Objectives
You will be able to: 
- Use pandas methods and attributes to access information about a dataset 
- Index pandas dataframes with .loc, .iloc, and column names 
- Use a boolean mask to index pandas series and dataframes

## Load the data

Load the file `'WorldCupMatches.csv'` as a DataFrame in Pandas.

In [116]:
# Import pandas using the standard alias
import pandas as pd

# Import 'WorldCupMatches.csv' as a DataFrame
df = pd.read_csv('WorldCupMatches.csv')

## Common methods and attributes

Use the correct method to look at the first 7 rows of the dataset.

In [117]:
# Print the first 7 rows of df
df.head(7)

   Year              Datetime  ... Home Team Initials Away Team Initials
0  1930  13 Jul 1930 - 15:00   ...                FRA                MEX
1  1930  13 Jul 1930 - 15:00   ...                USA                BEL
2  1930  14 Jul 1930 - 12:45   ...                YUG                BRA
3  1930  14 Jul 1930 - 14:50   ...                ROU                PER
4  1930  15 Jul 1930 - 16:00   ...                ARG                FRA
5  1930  16 Jul 1930 - 14:45   ...                CHI                MEX
6  1930  17 Jul 1930 - 12:45   ...                YUG                BOL

[7 rows x 20 columns]

Look at the last 3 rows of the data set.

In [118]:
# Print the last 3 rows of df
df.tail(3)

     Year              Datetime  ... Home Team Initials Away Team Initials
849  2014  09 Jul 2014 - 17:00   ...                NED                ARG
850  2014  12 Jul 2014 - 17:00   ...                BRA                NED
851  2014  13 Jul 2014 - 16:00   ...                GER                ARG

[3 rows x 20 columns]

Get a concise summary of the data using `.info()`.

In [119]:
# Print a concise summary of df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
Year                    852 non-null int64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null int64
Away Team Goals         852 non-null int64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null int64
Half-time Away Goals    852 non-null int64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null int64
MatchID                 852 non-null int64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtypes: float64(1), int64(7), object(12)
memory usage: 133.2+ KB

Obtain a tuple representing the number of rows and number of columns

In [120]:
# Print the number of rows and columns in df
df.shape

(852, 20)

Use the appropriate attribute to get the column names

In [121]:
# Print the column names of df
print(df.columns)

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

## Selecting DataFrame information

When looking at the DataFrame's `.head()`, you might have noticed that the games are structured chronologically in the DataFrame.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [122]:
# Print rows 3 through 5
df.iloc[3:6]

   Year              Datetime  ... Home Team Initials Away Team Initials
3  1930  14 Jul 1930 - 14:50   ...                ROU                PER
4  1930  15 Jul 1930 - 16:00   ...                ARG                FRA
5  1930  16 Jul 1930 - 14:45   ...                CHI                MEX

[3 rows x 20 columns]

Now, print all the info from game 5-9, but we're only interested in printing out the, "Home Team Name" and the, "Away Team Name."

In [123]:
#Print rows 5 through 9 and columns 'Home Team Name' and 'Away Team Name'
df.loc[5:9,['Home Team Name','Away Team Name']]

  Home Team Name Away Team Name
5          Chile         Mexico
6     Yugoslavia        Bolivia
7            USA       Paraguay
8        Uruguay           Peru
9          Chile         France

Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [124]:
# Print all info for games played in 1950 for Group 3
df.loc[(df['Year'] == 1950) & (df['Stage'] == 'Group 3')]

    Year              Datetime  ... Home Team Initials Away Team Initials
56  1950  25 Jun 1950 - 15:00   ...                SWE                ITA
61  1950  29 Jun 1950 - 15:30   ...                SWE                PAR
65  1950  02 Jul 1950 - 15:00   ...                ITA                PAR

[3 rows x 20 columns]

Let's repeat the command above, but now we only want to print out the attendance column for the Group 3 games.

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [125]:
# Print the 'Attendance' column for games played in 1950 for Group 3
df.loc[(df['Year']==1950) & (df['Stage']=='Group 3'), 'Attendance']

56    36502.0
61     7903.0
65    25811.0
Name: Attendance, dtype: float64

Throughout the entire history of the World Cup, how many home games were played by the Netherlands?

In [126]:
# Number of home games played by the Netherlands
df.loc[df['Home Team Name']=='Netherlands']

     Year               Datetime  ... Home Team Initials Away Team Initials
244  1974   19 Jun 1974 - 19:30   ...                NED                SWE
258  1974   26 Jun 1974 - 19:30   ...                NED                ARG
265  1974   03 Jul 1974 - 19:30   ...                NED                BRA
269  1974  07 July 1974 - 16:00   ...                NED                FRG
277  1978   03 Jun 1978 - 16:45   ...                NED                IRN
285  1978   07 Jun 1978 - 16:45   ...                NED                PER
295  1978   14 Jun 1978 - 13:45   ...                NED                AUT
302  1978   21 Jun 1978 - 13:45   ...                NED                ITA
422  1990   12 Jun 1990 - 21:00   ...                NED                EGY
472  1994   20 Jun 1994 - 19:30   ...                NED                KSA
504  1994   04 Jul 1994 - 12:00   ...                NED                IRL
509  1994   09 Jul 1994 - 14:30   ...                NED                BRA
525  1998   13 Jun 1998 - 21:00   ...                NED                BEL
542  1998   20 Jun 1998 - 21:00   ...                NED                KOR
557  1998   25 Jun 1998 - 16:00   ...                NED                MEX
569  1998   29 Jun 1998 - 21:00   ...                NED                YUG
574  1998   04 Jul 1998 - 16:30   ...                NED                ARG
578  1998   11 Jul 1998 - 21:00   ...                NED                CRO
665  2006   16 Jun 2006 - 18:00   ...                NED                CIV
682  2006   21 Jun 2006 - 21:00   ...                NED                ARG
716  2010   14 Jun 2010 - 13:30   ...                NED                DEN
731  2010   19 Jun 2010 - 13:30   ...                NED                JPN
760  2010   28 Jun 2010 - 16:00   ...                NED                SVK
764  2010   02 Jul 2010 - 16:00   ...                NED                BRA
771  2010   11 Jul 2010 - 20:30   ...                NED                ESP
805  2014   23 Jun 2014 - 13:00   ...                NED                CHI
829  2014   09 Jul 2014 - 17:00   ...                NED                ARG
830  2014   05 Jul 2014 - 17:00   ...                NED                CRC
832  2014   29 Jun 2014 - 13:00   ...                NED                MEX
838  2014   29 Jun 2014 - 13:00   ...                NED                MEX
847  2014   05 Jul 2014 - 17:00   ...                NED                CRC
849  2014   09 Jul 2014 - 17:00   ...                NED                ARG

[32 rows x 20 columns]

How many games were played by the Netherlands in total?

In [137]:
# Number of games played by the Netherlands in total
len(df.loc[(df['Home Team Name']=='Netherlands') | (df['Away Team Name']=='Netherlands')])

54

Next, let's try and figure out how many games the USA played in the 2014 World Cup.

In [128]:
# Number of games the USA played in the 2014 world cup
len(df.loc[((df['Home Team Name']=='USA') | (df['Away Team Name']=='USA')) & (df['Year']==2014)])

5

Now, let's try to find out how many countries participated in the 1986 World Cup.

Hint 1: as a first step, create a new dataset that only contains games in that year.

Hint 2: You can use `.unique()` to make sure you don't end up with duplicate country names.

In [129]:
import numpy as np

In [130]:
# Number of countries participated in the 1986 world cup
print(len(set(df.loc[(df['Year']==1986), 'Home Team Name'])))
print(len(np.unique(df.loc[(df['Year']==1986), 'Home Team Name'])))

24
24

In World Cup history, how many matches had 5 goals or more in total?

In [138]:
# Number of matches that had 5 or more goals in total
len(df.loc[(df['Home Team Goals']+df['Away Team Goals']>=5)])

147

## Changing values and creating new columns

With the information you currently have in your `df`, create a new column, "Half-time Goals."

In [132]:
# Create a new column 'Half-time Goals' in df
df['Half-time Goals'] = df['Half-time Away Goals']+df['Half-time Home Goals']

In [133]:
df

     Year              Datetime  ... Away Team Initials Half-time Goals
0    1930  13 Jul 1930 - 15:00   ...                MEX               3
1    1930  13 Jul 1930 - 15:00   ...                BEL               2
2    1930  14 Jul 1930 - 12:45   ...                BRA               2
3    1930  14 Jul 1930 - 14:50   ...                PER               1
4    1930  15 Jul 1930 - 16:00   ...                FRA               0
..    ...                   ...  ...                ...             ...
847  2014  05 Jul 2014 - 17:00   ...                CRC               0
848  2014  08 Jul 2014 - 17:00   ...                GER               5
849  2014  09 Jul 2014 - 17:00   ...                ARG               0
850  2014  12 Jul 2014 - 17:00   ...                NED               2
851  2014  13 Jul 2014 - 16:00   ...                ARG               0

[852 rows x 21 columns]

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [134]:
# Print all records containing the string 'Korea'
df.loc[df['Home Team Name'].str.contains('Korea'), 'Home Team Name']

179         Korea DPR
187         Korea DPR
374    Korea Republic
386    Korea Republic
434    Korea Republic
444    Korea Republic
480    Korea Republic
524    Korea Republic
593    Korea Republic
609    Korea Republic
635    Korea Republic
642    Korea Republic
655    Korea Republic
710    Korea Republic
753         Korea DPR
802    Korea Republic
818    Korea Republic
Name: Home Team Name, dtype: object

Imagine that, for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

In [135]:
# Update the 'Home Team Name' and 'Home Team Initials' columns 
df.loc[(df['Home Team Name']).str.contains('Korea'), 'Home Team Name'] = 'Korea'
df.loc[(df['Away Team Name']).str.contains('Korea'), 'Away Team Name'] = 'Korea'
df.loc[(df['Home Team Name']).str.contains('Korea'), 'Home Team Initials'] = 'NSK'
df.loc[(df['Away Team Name']).str.contains('Korea'), 'Away Team Initials'] = 'NSK'

Make sure to verify your answer!

In [136]:
# Check the updated columns
df.loc[(df['Home Team Name'] == 'Korea') | (df['Away Team Name'] == 'Korea')]

     Year              Datetime  ... Away Team Initials Half-time Goals
80   1954  17 Jun 1954 - 18:00   ...                NSK               4
88   1954  20 Jun 1954 - 17:00   ...                NSK               4
171  1966  12 Jul 1966 - 19:30   ...                NSK               2
179  1966  15 Jul 1966 - 19:30   ...                CHI               1
187  1966  19 Jul 1966 - 19:30   ...                ITA               1
195  1966  23 Jul 1966 - 15:00   ...                NSK               5
364  1986  02 Jun 1986 - 12:00   ...                NSK               2
374  1986  05 Jun 1986 - 16:00   ...                BUL               1
386  1986  10 Jun 1986 - 12:00   ...                ITA               1
421  1990  12 Jun 1990 - 17:00   ...                NSK               0
434  1990  17 Jun 1990 - 21:00   ...                ESP               2
444  1990  21 Jun 1990 - 17:00   ...                URU               0
464  1994  17 Jun 1994 - 19:30   ...                NSK               0
480  1994  23 Jun 1994 - 19:30   ...                BOL               0
490  1994  27 Jun 1994 - 16:00   ...                NSK               3
524  1998  13 Jun 1998 - 17:30   ...                MEX               1
542  1998  20 Jun 1998 - 21:00   ...                NSK               2
556  1998  25 Jun 1998 - 16:00   ...                NSK               1
593  2002  04 Jun 2002 - 20:30   ...                POL               1
609  2002  10 Jun 2002 - 15:30   ...                USA               1
625  2002  14 Jun 2002 - 20:30   ...                NSK               0
635  2002  18 Jun 2002 - 20:30   ...                ITA               0
639  2002  22 Jun 2002 - 15:30   ...                NSK               0
640  2002  25 Jun 2002 - 20:30   ...                NSK               0
642  2002  29 Jun 2002 - 20:00   ...                TUR               4
655  2006  13 Jun 2006 - 15:00   ...                TOG               1
672  2006  18 Jun 2006 - 21:00   ...                NSK               1
691  2006  23 Jun 2006 - 21:00   ...                NSK               1
710  2010  12 Jun 2010 - 13:30   ...                GRE               1
721  2010  15 Jun 2010 - 20:30   ...                NSK               0
725  2010  17 Jun 2010 - 13:30   ...                NSK               3
737  2010  21 Jun 2010 - 13:30   ...                NSK               1
742  2010  22 Jun 2010 - 20:30   ...                NSK               2
753  2010  25 Jun 2010 - 16:00   ...                CIV               2
756  2010  26 Jun 2010 - 16:00   ...                NSK               1
788  2014  17 Jun 2014 - 18:00   ...                NSK               0
802  2014  22 Jun 2014 - 16:00   ...                ALG               3
818  2014  26 Jun 2014 - 17:00   ...                BEL               0

[38 rows x 21 columns]

## Summary

In this lab, you learned how to access data within Pandas!